### PR TITLE
Project List Page

### PR DESCRIPTION
**Pull request by Ti-tanium**
image
image

### CODE REVIEW

**Comment by sidharthNair** [comment]
I am not getting the Create New Project pop up when clicking New Project. Has that code not been pushed yet?

**Comment by Ti-tanium** [comment]
> I am not getting the Create New Project pop up when clicking New Project. Has that code not been pushed yet?

weird, the code had been pushed.

**Comment by sidharthNair** [comment]
> 
> 
> > I am not getting the Create New Project pop up when clicking New Project. Has that code not been pushed yet?
> 
> weird, the code had been pushed.

I don't see code for interacting with the button to open the pop up (if that was the intent). Aside from that though the layout looks great and should be good to merge.

**Comment by Ti-tanium** [comment]
> > > I am not getting the Create New Project pop up when clicking New Project. Has that code not been pushed yet?
> > 
> > 
> > weird, the code had been pushed.
> 
> I don't see code for interacting with the button to open the pop up (if that was the intent). Aside from that though the layout looks great and should be good to merge.

this line `onClick={() => setShowNewProjectModal(true)}` should open the popup

**Pull request merged**
